### ISSUE TITLE
The add_many method does not commit to the DB

### ISSUE THREAD

**Issue by Adwaith-Rajesh** [avi-perl/PostHole#1]
https://github.com/avi-perl/PostHole/blob/master/app/databases.py#L24:L25

The add_many method in the `DBProxy` class does not commit  or call the `self.save()` method.

**Comment by avi-perl** [comment]
Hi Adwaith,

Thank you for your feedback and your contribution to the project in the form of your package `strip.pysondb`!

My goal with using a .json file as the db was simplicity and a free db for the project. Shortly after implementing this, SQLModel was released which allows me to maintain that simplicity while using SQLite or any other relational db! 

Having chosen to use SQLModel, this part of the code is no longer part of the project.
